(function () {
  window.FIELD_IDS = [
    "brandName",
    "classType",
    "alcoholContent",
    "netContents",
    "bottlerProducer",
    "productOrigin",
    "governmentWarning",
  ];

  window.DISPLAY_LABELS = {
    brandName: "Brand Name",
    classType: "Class / Type",
    alcoholContent: "Alcohol Content",
    netContents: "Net Contents",
    bottlerProducer: "Bottler / Producer",
    productOrigin: "Product Origin",
    governmentWarning: "Government Warning",
  };

  window.mockAnalysis = {
    fields: [
      {
        id: "brandName",
        label: "Brand Name",
        required: true,
        aiValue: "OLD TOM DISTILLERY",
        applicationValue: "OLD TOM DISTILLERY",
        userValue: null,
        status: "valid",
        confidence: 0.99,
        box: { x: 0.18, y: 0.16, w: 0.48, h: 0.18 },
        message: "",
        suggestion: "",
        checks: [],
      },
      {
        id: "classType",
        label: "Class / Type",
        required: true,
        aiValue: "Kentucky Straight Bourbon Whiskey",
        applicationValue: "Kentucky Straight Bourbon Whiskey",
        userValue: null,
        status: "valid",
        confidence: 0.98,
        box: { x: 0.28, y: 0.38, w: 0.4, h: 0.12 },
        message: "",
        suggestion: "",
        checks: [],
      },
      {
        id: "alcoholContent",
        label: "Alcohol Content",
        required: true,
        aiValue: "45% Alc./Vol. (90 Proof)",
        applicationValue: "45% Alc./Vol. (90 Proof)",
        userValue: null,
        status: "valid",
        confidence: 0.96,
        box: { x: 0.12, y: 0.57, w: 0.18, h: 0.09 },
        message: "",
        suggestion: "",
        checks: [],
      },
      {
        id: "netContents",
        label: "Net Contents",
        required: true,
        aiValue: "750 mL",
        applicationValue: "750 mL",
        userValue: null,
        status: "valid",
        confidence: 0.98,
        box: { x: 0.14, y: 0.67, w: 0.12, h: 0.06 },
        message: "",
        suggestion: "",
        checks: [],
      },
      {
        id: "bottlerProducer",
        label: "Bottler / Producer",
        required: true,
        aiValue: "Old Tom Distillery, LLC",
        applicationValue: "Old Tom Distillery, LLC",
        userValue: null,
        status: "valid",
        confidence: 0.97,
        box: { x: 0.12, y: 0.74, w: 0.28, h: 0.12 },
        message: "",
        suggestion: "",
        checks: [],
      },
      {
        id: "productOrigin",
        label: "Product Origin",
        required: false,
        aiValue: "Kentucky, USA",
        applicationValue: "Kentucky, USA",
        userValue: null,
        status: "warning",
        confidence: 0.9,
        box: { x: 0.72, y: 0.3, w: 0.12, h: 0.08 },
        message: "Verify origin statement.",
        suggestion: "",
        checks: [
          {
            id: "origin_uncertain",
            status: "warning",
            message: "AI is not fully confident this is an origin statement.",
          },
        ],
      },
      {
        id: "governmentWarning",
        label: "Government Warning",
        required: true,
        aiValue: "Government Warning",
        applicationValue: "GOVERNMENT WARNING:",
        userValue: null,
        status: "invalid",
        confidence: 0.42,
        box: { x: 0.56, y: 0.68, w: 0.34, h: 0.2 },
        message: "Heading must be \"GOVERNMENT WARNING:\" in ALL CAPS and bold.",
        suggestion: "GOVERNMENT WARNING:",
        checks: [
          {
            id: "warning_heading_caps",
            status: "invalid",
            message: "Heading must be all caps and bold.",
          },
        ],
      },
    ],
    summary: {
      total: 7,
      valid: 5,
      warning: 1,
      invalid: 1,
      corrected: 0,
    },
  };
})();
